services:
    db:
        image: postgres:latest
        container_name: hmon-backend-db
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: hmon
        volumes:
            - hmon-backend-db:/var/lib/postgresql/data
            - ../db/init.sql:/docker-entrypoint-initdb.d/init.sql
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "postgres"]
            interval: 5s
            timeout: 5s
            retries: 5

    app:
        build:
            context: ..
            dockerfile: docker/Dockerfile
        container_name: hmon-backend-app
        ports:
            - "3000:80"
        environment:
            NODE_ENV: development
            DB_HOST: db
            DB_PORT: 5432
            DB_NAME: hmon
            DB_USER: postgres
            DB_PASSWORD: postgres
            # TERMINAL_URL: http://172.23.23.111:8080
            TERMINAL_URL: http://192.168.178.33:8080
            CORS_WHITELIST: "*"
        volumes:
            - ../src:/app/src
            - ../logs:/app/logs
        depends_on:
            db:
                condition: service_healthy

volumes:
    hmon-backend-db:
