CREATE SCHEMA IF NOT EXISTS public;

CREATE TABLE IF NOT EXISTS public.shelly_plugs (
    id SERIAL PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name VARCHAR(100) NOT NULL,
    url VARCHAR(255) NOT NULL,
    protected BOOLEAN NOT NULL DEFAULT FALSE,
    is_on BOOLEAN NOT NULL DEFAULT FALSE
);